### ISSUE TITLE
Compatibilidad TOTAL de envío de memes.

### ISSUE THREAD

**Issue by FedeIsola** [Franco-Giordano/MegaChat#16]
Esto es un punto a desarrollar, no hay base de datos de memes, así que es una lastima. Pero podríamos implementar un buscador de memes, todo muy lógico por acá eh...
Que lindo día que hizo hoy che, ahora a la noche está un poquito más fresquito, pero bueno... *se ceba un mate*, ¿querés uno dulce?, uh, por la cara parece que no... Em bueno, creo que tengo que seguir pensando pelotudeces, te dejo el termito y el mate por acá. 
*Desaparece*

**Comment by Franco-Giordano** [comment]
le pones de label invalido pero aca el unico invalido sos vos
